#!/bin/bash
function start() {
	libs=$(find libs/ -name '*.jar' -exec echo -n :{} \;)
	libs=$libs:$(find . -maxdepth 1 -name '*.jar' -exec echo -n :{} \;)
	libs=${libs:1}
	
	java -cp "$libs" org.asf.edge.modules.gridapi.EdgeGridApiServerMain "$@"
	code=$?
	if [ "$code" == "237" ]; then
		start
		return
	fi
	exit $code
}

start
