#!/bin/bash
function start() {
	libs=$(find libs/ -name '*.jar' -exec echo -n :{} \;)
	libs=$libs:$(find . -maxdepth 1 -name '*.jar' -exec echo -n :{} \;)
	libs=${libs:1}
	
	java -cp "$libs" org.asf.edge.commonapi.EdgeCommonApiServerMain "$@"
	code=$?
	if [ "$code" == "0" ] && [ -f commonapiupdater.jar ]; then
		java -cp "commonapiupdater.jar" org.asf.edge.commonapi.EdgeCommonApiServerUpdater --update
		rm commonapiupdater.jar
		echo
		start
	fi
	exit $code
}

start
