package org.asf.edge.commonapi.http.handlers.api.core;

import java.io.IOException;

import org.asf.connective.RemoteClient;
import org.asf.connective.processors.HttpPushProcessor;
import org.asf.edge.common.http.apihandlerutils.BaseApiHandler;
import org.asf.edge.common.http.apihandlerutils.functions.Function;
import org.asf.edge.common.http.apihandlerutils.functions.FunctionInfo;
import org.asf.edge.commonapi.EdgeCommonApiServer;

public class ConfigurationWebServiceProcessor extends BaseApiHandler<EdgeCommonApiServer> {

	public ConfigurationWebServiceProcessor(EdgeCommonApiServer server) {
		super(server);
	}

	@Override
	public HttpPushProcessor createNewInstance() {
		return new ConfigurationWebServiceProcessor(getServerInstance());
	}

	@Override
	public String path() {
		return "/ConfigurationWebService.asmx";
	}

	@Override
	public void fallbackRequestProcessor(String path, String method, RemoteClient client, String contentType)
			throws IOException {
		// Handle request
		path = path;
		setResponseStatus(404, "Not found");
	}

	@Function(allowedMethods = { "POST" })
	public void getMMOServerInfoWithZone(FunctionInfo info) throws IOException {
		// Handle server list request
		ServiceRequestInfo req = getUtilities().getServiceRequestPayload(getServerInstance().getLogger());
		if (req == null)
			return;

		// Dummy
		setResponseContent("text/xml", "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
				+ "<ArrayOfMMOServerInfo xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns=\"http://api.jumpstart.com/\">\n"
				+ "  <MMOServerInfo>\n" + "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n"
				+ "    <PN xmlns=\"\">9933</PN>\n" + "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">FarmingThawfestDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubHiddenWorldNBDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HelheimsGateDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">RacingDragon</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">DEClubhouseINTDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">TargetPracticeDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">BerkCloudsDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HatcheryINTDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">GlacierIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubDragonsEdgeDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">ArmorWingIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">OpenOceanDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">GauntletDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubAuctionIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">GreatHallSchoolIntDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">DarkDeepDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">ShipGraveyardDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubHiddenWorldDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubDragonIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubTradewindIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubLookoutDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubEruptodonIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubSchoolDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubDragonIslandINTDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubVanaheimDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubArctic01DO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">TitanIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">MyRoomINTDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubBerkDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">FarmingDreadfallDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HobblegruntIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">PirateQueenShipDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubWarlordIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">GreatHallBerkIntDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">DragonRacingDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">ZipplebackIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">DarkDeepCavesDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">FarmingDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HatcheryINT02DO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">ScuttleclawIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubWilderness01DO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">FarmingOceanDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">CreditsDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubBerkNewDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubTrainingDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubDeathsongIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubArcticINTDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">ArenaFrenzyDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">MudrakerIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">BerkFarmDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-2.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubCenoteDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">FarmingThawfestDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubHiddenWorldNBDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HelheimsGateDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">RacingDragon</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">DEClubhouseINTDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">TargetPracticeDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">BerkCloudsDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HatcheryINTDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">GlacierIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubDragonsEdgeDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">ArmorWingIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">OpenOceanDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">GauntletDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubAuctionIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">GreatHallSchoolIntDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">DarkDeepDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">ShipGraveyardDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubHiddenWorldDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubDragonIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubTradewindIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubLookoutDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubEruptodonIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubSchoolDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubDragonIslandINTDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubVanaheimDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubArctic01DO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">TitanIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">MyRoomINTDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubBerkDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">FarmingDreadfallDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HobblegruntIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">PirateQueenShipDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubWarlordIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">GreatHallBerkIntDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">DragonRacingDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">ZipplebackIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">DarkDeepCavesDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">FarmingDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HatcheryINT02DO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">ScuttleclawIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubWilderness01DO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">FarmingOceanDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">CreditsDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubBerkNewDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubTrainingDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubDeathsongIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubArcticINTDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">ArenaFrenzyDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">MudrakerIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">BerkFarmDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-1.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubCenoteDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">FarmingThawfestDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">HubHiddenWorldNBDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">HelheimsGateDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">RacingDragon</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">DEClubhouseINTDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">TargetPracticeDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">BerkCloudsDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">HatcheryINTDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">GlacierIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">HubDragonsEdgeDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">ArmorWingIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">OpenOceanDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">GauntletDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">HubAuctionIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">GreatHallSchoolIntDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">DarkDeepDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">ShipGraveyardDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">HubHiddenWorldDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">HubDragonIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">HubTradewindIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">HubLookoutDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">HubEruptodonIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">HubSchoolDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">HubDragonIslandINTDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">HubVanaheimDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">HubArctic01DO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">TitanIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">MyRoomINTDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">HubBerkDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">FarmingDreadfallDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">HobblegruntIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">PirateQueenShipDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">HubWarlordIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">GreatHallBerkIntDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">DragonRacingDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">ZipplebackIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">DarkDeepCavesDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">FarmingDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">HatcheryINT02DO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">ScuttleclawIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">HubWilderness01DO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">FarmingOceanDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">CreditsDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">HubBerkNewDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">HubTrainingDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">HubDeathsongIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">HubArcticINTDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">ArenaFrenzyDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">MudrakerIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">BerkFarmDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-4.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">true</DF>\n"
				+ "    <ZN xmlns=\"\">HubCenoteDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">FarmingThawfestDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubHiddenWorldNBDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HelheimsGateDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">RacingDragon</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">DEClubhouseINTDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">TargetPracticeDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">BerkCloudsDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HatcheryINTDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">GlacierIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubDragonsEdgeDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">ArmorWingIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">OpenOceanDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">GauntletDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubAuctionIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">GreatHallSchoolIntDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">DarkDeepDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">ShipGraveyardDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubHiddenWorldDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubDragonIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubTradewindIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubLookoutDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubEruptodonIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubSchoolDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubDragonIslandINTDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubVanaheimDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubArctic01DO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">TitanIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">MyRoomINTDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubBerkDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">FarmingDreadfallDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HobblegruntIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">PirateQueenShipDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubWarlordIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">GreatHallBerkIntDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">DragonRacingDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">ZipplebackIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">DarkDeepCavesDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">FarmingDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HatcheryINT02DO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">ScuttleclawIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubWilderness01DO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">FarmingOceanDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">CreditsDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubBerkNewDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubTrainingDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubDeathsongIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubArcticINTDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">ArenaFrenzyDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">MudrakerIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">BerkFarmDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-6.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubCenoteDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">FarmingThawfestDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubHiddenWorldNBDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HelheimsGateDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">RacingDragon</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">DEClubhouseINTDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">TargetPracticeDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">BerkCloudsDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HatcheryINTDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">GlacierIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubDragonsEdgeDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">ArmorWingIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">OpenOceanDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">GauntletDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubAuctionIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">GreatHallSchoolIntDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">DarkDeepDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">ShipGraveyardDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubHiddenWorldDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubDragonIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubTradewindIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubLookoutDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubEruptodonIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubSchoolDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubDragonIslandINTDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubVanaheimDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubArctic01DO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">TitanIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">MyRoomINTDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubBerkDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">FarmingDreadfallDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HobblegruntIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">PirateQueenShipDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubWarlordIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">GreatHallBerkIntDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">DragonRacingDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">ZipplebackIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">DarkDeepCavesDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">FarmingDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HatcheryINT02DO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">ScuttleclawIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubWilderness01DO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">FarmingOceanDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">CreditsDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubBerkNewDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubTrainingDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubDeathsongIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubArcticINTDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">ArenaFrenzyDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">MudrakerIslandDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">BerkFarmDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "  <MMOServerInfo>\n"
				+ "    <IP xmlns=\"\">jumpstart-mmo2x-3.cloudapp.net</IP>\n" + "    <PN xmlns=\"\">9933</PN>\n"
				+ "    <VR xmlns=\"\">S2X</VR>\n" + "    <DF xmlns=\"\">false</DF>\n"
				+ "    <ZN xmlns=\"\">HubCenoteDO</ZN>\n" + "    <RZN xmlns=\"\">JumpStart</RZN>\n"
				+ "  </MMOServerInfo>\n" + "</ArrayOfMMOServerInfo>");
	}

}
